import Head from "next/head";
import Image from "next/future/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Himalaya</title>
        <meta name="description" content="Generated by admin" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout />
    </div>
  );
}
