import Head from "next/head";
import dynamic from "next/dynamic";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Himalaya</title>
        <meta name="description" content="Generated by admin" />
      </Head>
      <Layout />
    </div>
  );
}
