import Head from "next/head";
import Image from "next/future/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Himalaya</title>
        <meta name="description" content="Generated by admin" />
      </Head>
      <Layout />
    </div>
  );
}
